name: Bump Version

on:
  push:
    branches:
      - develop   # or the branch you want to track

permissions:
  contents: write   # allow workflow to push commits

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches the entire history
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Get last commit message for 'major', 'minor', 'patch' strings. Default to 'patch'
      # The behavior if commit message has both minor and major. 
      # Since the 'major' check comes first, any commit containing 'major' will always trigger a major bump, even if it also contains "minor"
      - name: Determine bump type
        id: bump
        run: |
          bump="patch"
          
          msg=$(git log -1 --pretty=%B)

          if echo "$msg" | grep -qi "major"; then
            bump="major"
          elif echo "$msg" | grep -qi "minor"; then
            bump="minor"
          fi

          echo "bump=$bump" >> $GITHUB_OUTPUT

      - name: Bump version
        run: |
          npm version ${{ steps.bump.outputs.bump }} --no-git-tag-version
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json package-lock.json || true
          git commit -m "ci: bump ${{ steps.bump.outputs.bump }} version [ci-trigger]" || echo "No changes to commit"
          git push
