name: Bump Version

on:
  push:
    branches:
      - develop   # or the branch you want to track

permissions:
  contents: write   # allow workflow to push commits

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches the entire history
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 
      - name: Determine bump type
        id: bump
        run: |
          # Default to patch
          bump="patch"

          # Get last commit message
          msg=$(git log -1 --pretty=%B)

          if echo "$msg" | grep -qi "major"; then
            bump="major"
          elif echo "$msg" | grep -qi "minor"; then
            bump="minor"
          fi

          echo "bump=$bump" >> $GITHUB_OUTPUT

      - name: Bump version
        run: |
          npm version patch --no-git-tag-version
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json package-lock.json || true
          git commit -m "ci: bump version [skip ci]" || echo "No changes to commit"
          git push
